#ifndef GAME_TEXT_ENUM_H
#define GAME_TEXT_ENUM_H

typedef enum {
    GAME_TEXT_ID_SELECTED_UNITS = 0,
    GAME_TEXT_ID_CMD_BAR_MOVE,
    GAME_TEXT_ID_CMD_BAR_STOP,
    GAME_TEXT_ID_CMD_BAR_ATTACK,
    GAME_TEXT_ID_CMD_BAR_DEFEND,
    GAME_TEXT_ID_CMD_BAR_CANCEL,
    GAME_TEXT_ID_NUMBER_OF_TEXTS
} GameTextIdEnum;

#endif /* GAME_TEXT_ENUM_H */
