#ifndef GAME_TEXT_ENUM_H
#define GAME_TEXT_ENUM_H

typedef enum {
    GAME_TEXT_ID_SELECTED_UNITS = 0,
    GAME_TEXT_ID_UNIT_SHEET_HP,
    GAME_TEXT_ID_UNIT_SHEET_DAMAGE,
    GAME_TEXT_ID_UNIT_SHEET_RANGE,
    GAME_TEXT_ID_UNIT_TYPE_WORKER,
	GAME_TEXT_ID_UNIT_TYPE_SOLDIER,
	GAME_TEXT_ID_UNIT_TYPE_ARCHER,
	GAME_TEXT_ID_UNIT_TYPE_MOUNT,
	GAME_TEXT_ID_UNIT_TYPE_MAGE,
	GAME_TEXT_ID_UNIT_TYPE_CITY_HALL,
	GAME_TEXT_ID_UNIT_TYPE_FARM,
	GAME_TEXT_ID_UNIT_TYPE_BARRACKS,
	GAME_TEXT_ID_UNIT_TYPE_BLACKSMITH,
	GAME_TEXT_ID_UNIT_TYPE_STABLES,
	GAME_TEXT_ID_UNIT_TYPE_TOWER,
    GAME_TEXT_ID_CMD_BAR_MOVE,
    GAME_TEXT_ID_CMD_BAR_STOP,
    GAME_TEXT_ID_CMD_BAR_ATTACK,
    GAME_TEXT_ID_CMD_BAR_DEFEND,
    GAME_TEXT_ID_CMD_BAR_CANCEL,
    GAME_TEXT_ID_NUMBER_OF_TEXTS
} GameTextIdEnum;

#endif /* GAME_TEXT_ENUM_H */
