#ifndef GAME_SOUND_H
#define GAME_SOUND_H
#include "common/sound.h"

#define MOD_VOICES 4
#define GAME_VOICES 4

typedef enum {
	GAME_MUSIC_INTRO,
	GAME_MUSIC_MENUS,
	GAME_MUSIC_VICTORY,
	GAME_MUSIC_DEFEAT,
	GAME_MUSIC_MAP_1,
	GAME_MUSIC_MAP_2,
	GAME_MUSIC_MAP_3,
    GAME_MUSIC_COUNT
} GameMusic;

typedef enum {
	GAME_SOUND_CLICK,
	GAME_SOUND_IRON_HIT,
	GAME_SOUND_CHOP,
	GAME_SOUND_GOLD_HIT,
	GAME_SOUND_WORK,
	GAME_SOUND_THROW_ARROW,
	GAME_SOUND_ARROW_HIT,
	GAME_SOUND_FIREBALL_LAUNCH,
	GAME_SOUND_FIREBALL_EXPLOSION,
	GAME_SOUND_BUILDING_BUILD,
	GAME_SOUND_BUILDING_CRUMBLE,
	GAME_SOUND_NOT_VALID,
	GAME_SOUND_DIE,
	GAME_SOUND_AJUM,
	GAME_SOUND_JA,
	GAME_SOUND_INCOMING_ATTACK,
	GAME_SOUNDS_COUNT
} GameSound;

void game_snd_play_music(GameMusic gameMusic);
void game_snd_play_sound(GameSound gameSound);
void game_snd_load_sounds();

#endif /* GAME_SOUND_H */
