#ifndef GAME_ENUMS_H
#define GAME_ENUMS_H

typedef enum {
	GAME_STATE_SPLASH,
	GAME_STATE_INTRO,
	GAME_STATE_TITLE,
	GAME_STATE_SCENARIO_SELECT,
	GAME_STATE_LOAD_MAP,
	GAME_STATE_PLAY_MAP,
	GAME_STATE_MENU_MAP,
	GAME_STATE_RESULTS,
	GAME_STATE_EXIT,
	NUM_GAME_STATES
} GameStateEnum;

typedef enum {
	RESOURCE_TYPE_GOLD,
	RESOURCE_TYPE_WOOD,
	RESOURCE_TYPE_AVAILABLE_FOOD,
	RESOURCE_TYPE_USED_FOOD,
	RESOURCE_TYPE_MAX_FOOD,
	RESOURCE_TYPES_COUNT,
	RESOURCE_TYPE_NONE
} ResourceTypeEnum;

typedef enum {
	BOARD_UNEXPLORED,
	BOARD_EXPLORED
} BoardExplorationEnum;

typedef enum {
	WALKABILITY_FREE,
	WALKABILITY_BLOCKED,
} WalkabilityEnum;

typedef enum {
	UNIT_TYPE_WORKER,
	UNIT_TYPE_SOLDIER,
	UNIT_TYPE_ARCHER,
	UNIT_TYPE_KNIGHT,
	UNIT_TYPE_MAGE,
	UNIT_TYPE_CITY_HALL,
	UNIT_TYPE_FARM,
	UNIT_TYPE_BARRACKS,
	UNIT_TYPE_BLACKSMITH,
	UNIT_TYPE_STABLES,
	UNIT_TYPE_TOWER,
	UNIT_TYPE_TURRET,
	UNIT_TYPE_NUMBER,
} UnitTypeEnum;

typedef enum {
	CMD_BAR_BUTTON_ICON_MOVE,
	CMD_BAR_BUTTON_ICON_STOP,
	CMD_BAR_BUTTON_ICON_ATTACK,
	CMD_BAR_BUTTON_ICON_DEFEND,
	CMD_BAR_BUTTON_ICON_CANCEL,
	CMD_BAR_BUTTON_ICON_BUILD,
	CMD_BAR_BUTTON_ICON_REPAIR,
	CMD_BAR_BUTTON_ICON_REPAIR_HARVEST,
	CMD_BAR_BUTTON_ICON_UPGRADE_SOLDIER,
	CMD_BAR_BUTTON_ICON_UPGRADE_ARCHER,
	CMD_BAR_BUTTON_ICON_UPGRADE_KNIGHT,
	CMD_BAR_BUTTON_ICON_UPGRADE_MAGE,
	CMD_BAR_BUTTON_ICON_TRAIN_WORKER,
	CMD_BAR_BUTTON_ICON_TRAIN_SOLDIER,
	CMD_BAR_BUTTON_ICON_TRAIN_ARCHER,
	CMD_BAR_BUTTON_ICON_TRAIN_KNIGHT,
	CMD_BAR_BUTTON_ICON_TRAIN_MAGE,
	CMD_BAR_BUTTON_ICON_BUILD_CITY_HALL,
	CMD_BAR_BUTTON_ICON_BUILD_FARM,
	CMD_BAR_BUTTON_ICON_BUILD_BARRACKS,
	CMD_BAR_BUTTON_ICON_BUILD_BLACKSMITH,
	CMD_BAR_BUTTON_ICON_BUILD_STABLES,
	CMD_BAR_BUTTON_ICON_BUILD_TOWER,
	CMD_BAR_BUTTON_ICON_BUILD_TURRET,
	CMD_BAR_BUTTON_ICON_COUNT,
} CommandBarButtonIconEnum;

typedef enum {
	TRAINING_TYPE_WORKER,
	TRAINING_TYPE_SOLDIER,
	TRAINING_TYPE_ARCHER,
	TRAINING_TYPE_KNIGHT,
	TRAINING_TYPE_MAGE,
	TRAINING_TYPE_CITY_HALL,
	TRAINING_TYPE_FARM,
	TRAINING_TYPE_BARRACKS,
	TRAINING_TYPE_BLACKSMITH,
	TRAINING_TYPE_STABLES,
	TRAINING_TYPE_TOWER,
	TRAINING_TYPE_TURRET,
	TRAINING_TYPE_UPGRADE_SOLDIER,
	TRAINING_TYPE_UPGRADE_ARCHER,
	TRAINING_TYPE_UPGRADE_KNIGHT,
	TRAINING_TYPE_UPGRADE_MAGE,
	TRAINING_TYPE_NUMBER,
} TrainingTypeEnum;

typedef enum {
	UNIT_CONTROLLER_PLAYER,
	UNIT_CONTROLLER_AI,
	UNIT_CONTROLLERS_COUNT,
} ControllerEnum;

typedef enum {
	UNIT_STATE_IDLE,
	UNIT_STATE_ATTACK,
	UNIT_STATE_DEFEND,
	UNIT_STATE_MOVE,
	UNIT_STATE_MOVE_ANIM,
	UNIT_STATE_MOVE_ATTACK,
	UNIT_STATE_WORK,
	UNIT_STATE_DIE,
	UNIT_STATES_COUNT,
} UnitStateEnum;

typedef enum {
	DIRECTION_NORTH,
	DIRECTION_EAST,
	DIRECTION_SOUTH,
	DIRECTION_WEST,
	DIRECTIONS_COUNT,
} DirectionEnum;

typedef enum {
	OBJ_DIRECTION_NORTH,
	OBJ_DIRECTION_NORTH_EAST,
	OBJ_DIRECTION_EAST,
	OBJ_DIRECTION_SOUTH_EAST,
	OBJ_DIRECTION_SOUTH,
	OBJ_DIRECTION_SOUTH_WEST,
	OBJ_DIRECTION_WEST,
	OBJ_DIRECTION_NORTH_WEST,
	OBJ_DIRECTIONS_COUNT,
} ObjectDirectionEnum;

typedef enum {
	EVENT_TYPE_SOUND,
	EVENT_TYPE_DAMAGE,
	EVENT_TYPE_AREA_DAMAGE,
	EVENT_TYPE_SPAWN_ARROW,
	EVENT_TYPE_SPAWN_FIREBALL,
	EVENT_TYPE_WORK,
	EVENT_TYPE_WORK_SOUND,
} EventType;

typedef enum {
	ANIMATION_TYPE_ONCE,
	ANIMATION_TYPE_CYCLE,
} AnimationType;

typedef enum {
	OBJ_TYPE_ARROW,
	OBJ_TYPE_FIREBALL,
	OBJ_TYPE_EXPLOSION,
	OBJ_TYPE_ARROW_DAMAGE,
	OBJ_TYPE_FLAG,
	OBJ_TYPE_NUMBER,
} ObjectTypeEnum;

typedef enum {
	LIFE_BAR_ALWAYS,
	LIFE_BAR_DAMAGED,
	LIFE_BAR_NEVER,
	LIFE_BAR_COUNT,
} LifeBarEnum;

typedef enum {
	LIFE_BAR_STYLE_BLACK_BAR,
	LIFE_BAR_STYLE_BLACK_BORDER,
	LIFE_BAR_STYLE_COUNT,
} LifeBarStyleEnum;

typedef enum {
    LANGUAGE_SPANISH = 0,
    LANGUAGE_ENGLISH = 1,
} GameLanguageEnum;

typedef enum {
	STRATEGY_HARVEST,
	STRATEGY_BUILD,
	STRATEGY_TRAIN,
	STRATEGY_ATTACK,
	STRATEGY_COUNT,
} ComputerStrategyEnum;

typedef enum {
	CMD_BAR_BTN_STATE_IDLE,
	CMD_BAR_BTN_STATE_HOVER,
	CMD_BAR_BTN_STATE_DOWN,
	CMD_BAR_BTN_STATE_RELEASED,
} CommandBarButtonStateEnum;

typedef enum {
	CMD_BAR_BTN_TYPE_ACTION,
	CMD_BAR_BTN_TYPE_CREATE,
} CommandBarButtonTypeEnum;

typedef enum {
	CMD_BAR_BUILD_STATE_NONE,
	CMD_BAR_BUILD_STATE_SELECT,
	CMD_BAR_BUILD_STATE_SELECT_ADVANCED,
	CMD_BAR_BUILD_STATE_PLACE,
} BuildingStateEnum;

typedef enum {
	GAME_RESULT_ONGOING,
	GAME_RESULT_VICTORY,
	GAME_RESULT_DEFEAT,
} GameResultEnum;

typedef enum {
	TILE_TYPE_WALKABLE,
	TILE_TYPE_BLOCKED,
	TILE_TYPE_WOOD,
	TILE_TYPE_GOLD,
	TILE_TYPE_WALL,
} TileTypeEnum;

typedef enum {
	AI_MODE_IDLE,
	AI_MODE_PASSIVE,
	AI_MODE_AGGRESSIVE,
} AIModeEnum;

typedef enum {
	AI_STATE_CREATE_WORKERS,
	AI_STATE_BUILDER_WORKERS,
	AI_STATE_HARVESTER_WORKERS,
	AI_STATE_TRAIN_UNITS,
	AI_STATE_SEND_ATTACK_UNITS,
	AI_STATE_COUNT,
} AIStateEnum;

typedef enum {
	WORKER_JOB_NONE,
	WORKER_JOB_GOLD,
	WORKER_JOB_WOOD,
	WORKER_JOB_REPAIR,
} WorkerJobEnum;

#endif /* GAME_ENUMS_H */
