#ifndef GAME_VIDEO_H
#define GAME_VIDEO_H
#include "../../common/common.h"

#define GAME_INTERNAL_WIDTH 320
#define GAME_INTERNAL_HEIGHT 200
#ifdef DOS
#define GAME_EXTERNAL_WIDTH GAME_INTERNAL_WIDTH
#define GAME_EXTERNAL_HEIGHT GAME_INTERNAL_HEIGHT
#else
#define GAME_EXTERNAL_WIDTH GAME_INTERNAL_WIDTH * 3
#define GAME_EXTERNAL_HEIGHT GAME_INTERNAL_HEIGHT * 3
#endif

#define GAME_COLOR_DEPTH 8

#define BACKGROUND_Z_ORDER 0
#define SPRITES_Z_ORDER 1000
#define UI_Z_ORDER 2000
#define MOUSE_Z_ORDER 3000

#endif /* GAME_VIDEO_H */