#ifndef GAME_VIDEO_H
#define GAME_VIDEO_H
#include "game/game_lib.h"

#define GAME_INTERNAL_WIDTH 320
#define GAME_INTERNAL_HEIGHT 200
#ifdef DOS
#define GAME_EXTERNAL_WIDTH GAME_INTERNAL_WIDTH
#define GAME_EXTERNAL_HEIGHT GAME_INTERNAL_HEIGHT
#else
#define GAME_EXTERNAL_WIDTH GAME_INTERNAL_WIDTH * 3
#define GAME_EXTERNAL_HEIGHT ( (int) (GAME_INTERNAL_HEIGHT * 3.6) )
#endif

#define GAME_COLOR_DEPTH 8

#define BACKGROUND_Z_ORDER 0
#define SPRITES_Z_ORDER 1000
#define OBJECTS_Z_ORDER 2000
#define UI_Z_ORDER 3000
#define MOUSE_Z_ORDER 4000

#define UNIVERSAL_PAL_FIRST_INDEX 32
#define UNIVERSAL_PAL_LAST_INDEX 247

typedef enum {
	PAL_COLOR_TRANS,
	PAL_COLOR_WHITE,
	PAL_COLOR_BLACK,
	PAL_COLOR_GREEN,
	PAL_COLOR_YELLOW,
	PAL_COLOR_RED,
	PAL_COLOR_GRAY,
	PAL_COLOR_DARK_GREEN,
	PAL_COLOR_DARK_GRAY,
	PAL_COLOR_TURQUOISE,
	PAL_COLOR_DARK_TURQUOISE,
	PAL_COLOR_CMD_BUTTON,
	PAL_COLOR_PLAYER,
	PAL_COLOR_COMPUTER,
	PAL_COLOR_VIOLET,
} PalColorsEnum;

InitializationStatusEnum game_video_load_universal_pal();

#endif /* GAME_VIDEO_H */
